base_url = "https://invicta.neocities.org"

compile_sass = true
build_search_index = false
generate_feed = false
feed_filename = "atom.xml"

[markdown]
# Whether to do syntax highlighting
highlight_code = true
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[extra]
menu = [
    { text = "index", link = "/" },
    { text = "about", link = "/about/" },
    { text = "journal", link = "/journal/" },
    { text = "dreams", link = "/dreams/" },
    { text = "fics", link = "/fics/" },
    { text = "links", link = "/links/" }
]